# -*- coding: utf-8 -*-
"""Unit_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBr98RARlZ_8WFkB0qUoO_ihzAbV_27L
"""

class ArrayList:
    def __init__(self):
        self.array = []

    def add(self, element):
        self.array.append(element)

    def get(self, index):
        if index < 0 or index >= len(self.array):
            raise IndexError("Index out of bounds")
        return self.array[index]

    def remove(self, index):
        if index < 0 or index >= len(self.array):
            raise IndexError("Index out of bounds")
        return self.array.pop(index)

import unittest

class TestArrayList(unittest.TestCase):
    def setUp(self):
        self.list = ArrayList()

    def test_add_element(self):
        self.list.add(1)
        self.assertEqual(self.list.get(0), 1)

    def test_get_element_valid_index(self):
        self.list.add(1)
        self.list.add(2)
        self.assertEqual(self.list.get(1), 2)

    def test_get_element_invalid_index(self):
        with self.assertRaises(IndexError):
            self.list.get(1)

    def test_remove_element_valid_index(self):
        self.list.add(1)
        self.list.add(2)
        removed_element = self.list.remove(0)
        self.assertEqual(removed_element, 1)
        self.assertEqual(self.list.get(0), 2)

    def test_remove_element_invalid_index(self):
        with self.assertRaises(IndexError):
            self.list.remove(1)

    def test_add_and_remove_multiple_elements(self):
        for i in range(5):
            self.list.add(i)
        for i in range(5):
            self.assertEqual(self.list.remove(0), i)
        with self.assertRaises(IndexError):
            self.list.get(0)

if __name__ == '__main__':
    unittest.main()

